Repository elks-org/elks, pull requests merged in 2020-02, with the labels that each got.

#292 [boot] shrink bootblocks code via various tricks
  elkscmd/bootblocks/Makefile
  elkscmd/bootblocks/boot_minix.c
  elkscmd/bootblocks/boot_sect.S
Labels: improvement

#295 [boot] (take 2) put boot_minix.c's entry point at sector start
  elkscmd/bootblocks/Makefile
  elkscmd/bootblocks/boot_minix.c
  elkscmd/bootblocks/boot_sect.S
Labels: improvement

#294 [image] Application Package Management for multiple disk images
  elks/tools/mfs/genfs.c
  elks/tools/mfs/main.c
  elks/tools/mfs/protos.h
  image/Make.defs
  image/Make.package
  image/Makefile
  image/Packages
Labels: enhancement

#297 [image] Cleanup MSDOS disk image creation and format
  elks/tools/mfs/main.c
  elks/tools/mfs/mkfs.c
  image/Make.package
  image/Makefile
  image/Packages
Labels: improvement

#301 [image] Remove 320k image builds from package manager
  image/Makefile
Labels: improvement

#305 [kernel] FAT filesystem rework : devfs & fixups
  elks/fs/msdos/dir.c
  elks/fs/msdos/fat.c
  elks/fs/msdos/file.c
  elks/fs/msdos/inode.c
  elks/fs/msdos/misc.c
  elks/fs/msdos/namei.c
  elks/include/linuxmt/msdos_fs_sb.h
  image/Make.package
  image/Packages
Labels: improvement

#300 [boot] rewrite & unify code for reading stage 2 booter & kernel
  elkscmd/bootblocks/boot_probe.S
  elkscmd/bootblocks/boot_sect.S
Labels: improvement

#315 [fat] Add fsdebug() macro for FAT filesystem debugging
  elks/fs/inode.c
  elks/fs/minix/bitmap.c
  elks/fs/msdos/fat.c
  elks/fs/msdos/file.c
  elks/fs/msdos/inode.c
  elks/fs/msdos/misc.c
  elks/fs/msdos/namei.c
  elks/include/linuxmt/msdos_fs.h
  elks/lib/chqueue.c
Labels: improvement

#316 [boot] Tweak makefile to honour $(ASFLAGS), and further shrink boot sector code
  elkscmd/bootblocks/Makefile
  elkscmd/bootblocks/boot_sect.S
Labels: improvement

#318 [fat] Fix longstanding system crash on FAT directory write
  elks/fs/inode.c
  elks/fs/msdos/dir.c
  elks/fs/msdos/fat.c
  elks/fs/msdos/file.c
  elks/fs/msdos/inode.c
  elks/fs/msdos/misc.c
  elks/fs/msdos/namei.c
  elks/include/linuxmt/fs.h
  elks/include/linuxmt/kdev_t.h
  elks/include/linuxmt/msdos_fs.h
  image/Make.package
  image/Makefile
Labels: fix

#319 [boot] Attempt to fit a /linux bootloader for FAT12/16 within 512 bytes
  elkscmd/bootblocks/Makefile
  elkscmd/bootblocks/boot_sect.S
  elkscmd/bootblocks/boot_sect_fat.h
Labels: enhancement

#321 [kernel] Fix: `head -1 /dev/fd1' gave /dev/fd0 contents instead
  elks/fs/block_dev.c
Labels: fix

#322 [fat] Fix everything required for ELKS to boot on FAT
  elks/fs/exec.c
  elks/fs/msdos/file.c
  elks/fs/msdos/inode.c
  elks/fs/msdos/misc.c
  elks/init/main.c
  elks/tools/mfs/genfs.c
  elkscmd/ash/Makefile
  elkscmd/inet/httpd/sample_index.html
  elkscmd/rootfs_template/etc/inittab
  elkscmd/rootfs_template/etc/rc.d/rc.sys
  elkscmd/sys_utils/init.c
  image/Make.package
  image/Makefile
  image/Packages
Labels: improvement

#325 [boot] Fix build for ROMFS or hard disk
  elkscmd/bootblocks/Makefile
  elkscmd/bootblocks/boot_sect.S
  elkscmd/bootblocks/boot_sect_fat.h
Labels: fix

#326 [image] Fix "make images-fat" build
  elks/tools/mfs/genfs.c
  image/Make.package
  image/Makefile
Labels: fix

#328 [fat] Finish up 360k, 720k, 1440k and 2880k FAT boot images
  elks/tools/setboot/setboot.c
  elkscmd/bootblocks/boot_sect.S
  elkscmd/bootblocks/boot_sect_fat.h
  image/Make.package
  image/Makefile
Labels: improvement

#330 [fat] More FAT build tuning
  elks/tools/setboot/setboot.c
  elkscmd/sh_utils/date.c
  image/Make.package
Labels: improvement

#333 Three minor improvements (in README.md, boot sector, & elksemu)
  README.md
  elkscmd/bootblocks/boot_sect.S
  elksemu/elks.c
  elksemu/elks_sys.c
Labels: improvement

#335 [image] FAT image in .config
  elks/arch/i86/defconfig
  elks/fs/config.in
  image/Make.defs
  image/Makefile
  image/Packages
  image/config.in
Labels: improvement

#336 [busyelks] More patches from mailing list
  busyelks/cmd.h
  busyelks/cmd/du.c
  busyelks/cmd/echo.c
  busyelks/cmd/ed.c
  busyelks/cmd/fdisk.c
  busyelks/cmd/find.c
  busyelks/config.h
  busyelks/config.mk
  busyelks/fdisk.h
  busyelks/main.c
  busyelks/makefile
Labels: improvement

#338 [qemu] Add OSX support and package manager testing to qemu.sh script
  qemu.sh
Labels: improvement

#337 [chmem] Add ELKS chmem command
  elkscmd/sys_utils/Makefile
  elkscmd/sys_utils/chmem.c
  image/Packages
Labels: enhancement

#339 [nanox] Include landmine game rather than nclock for Nano-X demo
  elkscmd/nano-X/Makefile
  image/Packages
Labels: improvement

#340 LD scripts: allow setting non-static data size, via a _chmem variable
  elks/elks-small.ld
  elks/elks-tiny.ld
  elksemu/elks.c
  elksemu/elks.h
Labels: improvement

#345 [image] Remove unneeded chmod from image generation template
  image/Makefile
Labels: improvement

#346 [elksemu] Fix gremlins making elksemu fail on openSUSE 13.2 x64
  elksemu/elks.c
Labels: fix
